//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("DB_128040_lovesModel", "FK_StorePrice_Grade", "Grade", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Loves_WPF.Grade), "StorePrice", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Loves_WPF.StorePrice), true)]
[assembly: EdmRelationshipAttribute("DB_128040_lovesModel", "FK_StorePrice_Store", "Store", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Loves_WPF.Store), "StorePrice", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Loves_WPF.StorePrice), true)]

#endregion

namespace Loves_WPF
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class DB_128040_lovesEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new DB_128040_lovesEntities object using the connection string found in the 'DB_128040_lovesEntities' section of the application configuration file.
        /// </summary>
        public DB_128040_lovesEntities() : base("name=DB_128040_lovesEntities", "DB_128040_lovesEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new DB_128040_lovesEntities object.
        /// </summary>
        public DB_128040_lovesEntities(string connectionString) : base(connectionString, "DB_128040_lovesEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new DB_128040_lovesEntities object.
        /// </summary>
        public DB_128040_lovesEntities(EntityConnection connection) : base(connection, "DB_128040_lovesEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Grade> Grades
        {
            get
            {
                if ((_Grades == null))
                {
                    _Grades = base.CreateObjectSet<Grade>("Grades");
                }
                return _Grades;
            }
        }
        private ObjectSet<Grade> _Grades;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Store> Stores
        {
            get
            {
                if ((_Stores == null))
                {
                    _Stores = base.CreateObjectSet<Store>("Stores");
                }
                return _Stores;
            }
        }
        private ObjectSet<Store> _Stores;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<StorePrice> StorePrices
        {
            get
            {
                if ((_StorePrices == null))
                {
                    _StorePrices = base.CreateObjectSet<StorePrice>("StorePrices");
                }
                return _StorePrices;
            }
        }
        private ObjectSet<StorePrice> _StorePrices;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Grades EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToGrades(Grade grade)
        {
            base.AddObject("Grades", grade);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Stores EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToStores(Store store)
        {
            base.AddObject("Stores", store);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the StorePrices EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToStorePrices(StorePrice storePrice)
        {
            base.AddObject("StorePrices", storePrice);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DB_128040_lovesModel", Name="Grade")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Grade : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Grade object.
        /// </summary>
        /// <param name="gradeId">Initial value of the GradeId property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        public static Grade CreateGrade(global::System.Int32 gradeId, global::System.String name)
        {
            Grade grade = new Grade();
            grade.GradeId = gradeId;
            grade.Name = name;
            return grade;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 GradeId
        {
            get
            {
                return _GradeId;
            }
            set
            {
                if (_GradeId != value)
                {
                    OnGradeIdChanging(value);
                    ReportPropertyChanging("GradeId");
                    _GradeId = StructuralObject.SetValidValue(value, "GradeId");
                    ReportPropertyChanged("GradeId");
                    OnGradeIdChanged();
                }
            }
        }
        private global::System.Int32 _GradeId;
        partial void OnGradeIdChanging(global::System.Int32 value);
        partial void OnGradeIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false, "Name");
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DB_128040_lovesModel", "FK_StorePrice_Grade", "StorePrice")]
        public EntityCollection<StorePrice> StorePrices
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<StorePrice>("DB_128040_lovesModel.FK_StorePrice_Grade", "StorePrice");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<StorePrice>("DB_128040_lovesModel.FK_StorePrice_Grade", "StorePrice", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DB_128040_lovesModel", Name="Store")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Store : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Store object.
        /// </summary>
        /// <param name="storeId">Initial value of the StoreId property.</param>
        /// <param name="threshold">Initial value of the Threshold property.</param>
        public static Store CreateStore(global::System.Int32 storeId, global::System.Decimal threshold)
        {
            Store store = new Store();
            store.StoreId = storeId;
            store.Threshold = threshold;
            return store;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 StoreId
        {
            get
            {
                return _StoreId;
            }
            set
            {
                if (_StoreId != value)
                {
                    OnStoreIdChanging(value);
                    ReportPropertyChanging("StoreId");
                    _StoreId = StructuralObject.SetValidValue(value, "StoreId");
                    ReportPropertyChanged("StoreId");
                    OnStoreIdChanged();
                }
            }
        }
        private global::System.Int32 _StoreId;
        partial void OnStoreIdChanging(global::System.Int32 value);
        partial void OnStoreIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal Threshold
        {
            get
            {
                return _Threshold;
            }
            set
            {
                OnThresholdChanging(value);
                ReportPropertyChanging("Threshold");
                _Threshold = StructuralObject.SetValidValue(value, "Threshold");
                ReportPropertyChanged("Threshold");
                OnThresholdChanged();
            }
        }
        private global::System.Decimal _Threshold;
        partial void OnThresholdChanging(global::System.Decimal value);
        partial void OnThresholdChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DB_128040_lovesModel", "FK_StorePrice_Store", "StorePrice")]
        public EntityCollection<StorePrice> StorePrices
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<StorePrice>("DB_128040_lovesModel.FK_StorePrice_Store", "StorePrice");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<StorePrice>("DB_128040_lovesModel.FK_StorePrice_Store", "StorePrice", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DB_128040_lovesModel", Name="StorePrice")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class StorePrice : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new StorePrice object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="storeNumber">Initial value of the StoreNumber property.</param>
        /// <param name="grade">Initial value of the Grade property.</param>
        /// <param name="previousPrice">Initial value of the PreviousPrice property.</param>
        /// <param name="newPrice">Initial value of the NewPrice property.</param>
        /// <param name="priceDifference">Initial value of the PriceDifference property.</param>
        /// <param name="timeStamp">Initial value of the TimeStamp property.</param>
        public static StorePrice CreateStorePrice(global::System.Int32 id, global::System.Int32 storeNumber, global::System.Int32 grade, global::System.Decimal previousPrice, global::System.Decimal newPrice, global::System.Decimal priceDifference, global::System.DateTime timeStamp)
        {
            StorePrice storePrice = new StorePrice();
            storePrice.Id = id;
            storePrice.StoreNumber = storeNumber;
            storePrice.Grade = grade;
            storePrice.PreviousPrice = previousPrice;
            storePrice.NewPrice = newPrice;
            storePrice.PriceDifference = priceDifference;
            storePrice.TimeStamp = timeStamp;
            return storePrice;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value, "Id");
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 StoreNumber
        {
            get
            {
                return _StoreNumber;
            }
            set
            {
                OnStoreNumberChanging(value);
                ReportPropertyChanging("StoreNumber");
                _StoreNumber = StructuralObject.SetValidValue(value, "StoreNumber");
                ReportPropertyChanged("StoreNumber");
                OnStoreNumberChanged();
            }
        }
        private global::System.Int32 _StoreNumber;
        partial void OnStoreNumberChanging(global::System.Int32 value);
        partial void OnStoreNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Grade
        {
            get
            {
                return _Grade;
            }
            set
            {
                OnGradeChanging(value);
                ReportPropertyChanging("Grade");
                _Grade = StructuralObject.SetValidValue(value, "Grade");
                ReportPropertyChanged("Grade");
                OnGradeChanged();
            }
        }
        private global::System.Int32 _Grade;
        partial void OnGradeChanging(global::System.Int32 value);
        partial void OnGradeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal PreviousPrice
        {
            get
            {
                return _PreviousPrice;
            }
            set
            {
                OnPreviousPriceChanging(value);
                ReportPropertyChanging("PreviousPrice");
                _PreviousPrice = StructuralObject.SetValidValue(value, "PreviousPrice");
                ReportPropertyChanged("PreviousPrice");
                OnPreviousPriceChanged();
            }
        }
        private global::System.Decimal _PreviousPrice;
        partial void OnPreviousPriceChanging(global::System.Decimal value);
        partial void OnPreviousPriceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal NewPrice
        {
            get
            {
                return _NewPrice;
            }
            set
            {
                OnNewPriceChanging(value);
                ReportPropertyChanging("NewPrice");
                _NewPrice = StructuralObject.SetValidValue(value, "NewPrice");
                ReportPropertyChanged("NewPrice");
                OnNewPriceChanged();
            }
        }
        private global::System.Decimal _NewPrice;
        partial void OnNewPriceChanging(global::System.Decimal value);
        partial void OnNewPriceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal PriceDifference
        {
            get
            {
                return _PriceDifference;
            }
            set
            {
                OnPriceDifferenceChanging(value);
                ReportPropertyChanging("PriceDifference");
                _PriceDifference = StructuralObject.SetValidValue(value, "PriceDifference");
                ReportPropertyChanged("PriceDifference");
                OnPriceDifferenceChanged();
            }
        }
        private global::System.Decimal _PriceDifference;
        partial void OnPriceDifferenceChanging(global::System.Decimal value);
        partial void OnPriceDifferenceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime TimeStamp
        {
            get
            {
                return _TimeStamp;
            }
            set
            {
                OnTimeStampChanging(value);
                ReportPropertyChanging("TimeStamp");
                _TimeStamp = StructuralObject.SetValidValue(value, "TimeStamp");
                ReportPropertyChanged("TimeStamp");
                OnTimeStampChanged();
            }
        }
        private global::System.DateTime _TimeStamp;
        partial void OnTimeStampChanging(global::System.DateTime value);
        partial void OnTimeStampChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DB_128040_lovesModel", "FK_StorePrice_Grade", "Grade")]
        public Grade Grade1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Grade>("DB_128040_lovesModel.FK_StorePrice_Grade", "Grade").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Grade>("DB_128040_lovesModel.FK_StorePrice_Grade", "Grade").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Grade> Grade1Reference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Grade>("DB_128040_lovesModel.FK_StorePrice_Grade", "Grade");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Grade>("DB_128040_lovesModel.FK_StorePrice_Grade", "Grade", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DB_128040_lovesModel", "FK_StorePrice_Store", "Store")]
        public Store Store
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Store>("DB_128040_lovesModel.FK_StorePrice_Store", "Store").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Store>("DB_128040_lovesModel.FK_StorePrice_Store", "Store").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Store> StoreReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Store>("DB_128040_lovesModel.FK_StorePrice_Store", "Store");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Store>("DB_128040_lovesModel.FK_StorePrice_Store", "Store", value);
                }
            }
        }

        #endregion

    }

    #endregion

}
